version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-and-auth-gcloud:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '18.10'
      - run: node --version
      - run:
          # Export base64 encoded google-services.json
          # into local bash variables
          name: Export Google Services Json
          command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
      - run:
          # Decode the base64 string
          name: Decode Google Services Json
          command: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
      - run: | 
          gcloud auth activate-service-account --key-file=app/google-services.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
workflows:
  setup-app:
    jobs:
      - install-and-auth-gcloud
