name: deploy all apps to prod

on:
    push:
        branches-ignore: [prod,main]

jobs:
    pre-job:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel redundant workflows
              uses: technote-space/auto-cancel-redundant-workflow@v1

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install vercel
              run: npm i vercel -g

            - name: Deploy landing page
              run: |
                export TEST=$(vercel --token $VERCEL_TOKEN) && echo "$TEST"
                export DISCORD_WEBHOOK=https://discord.com/api/webhooks/996044031127724116/5KXFIVDVDhwgAxEF5ECU1B9yPKcamEJe8WG7Yp61vDF4dvXxdRwK7fS-O1oYAOXhIT5B
                curl -H "Content-Type: application/json" -d '{"username": "Deployment", "content": "$VERCEL_LINK"}' $WEBHOOK_URL
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_LANDING_ORG }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LANDING_PROJ }}
            - name: Show logs
              run: vercel logs metapass-v2-anoushk1234.vercel.app --token $VERCEL_TOKEN
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_LANDING_ORG }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LANDING_PROJ }}
