name: deploy all apps to prod


on:
    push:
        branches-ignore: [prod,main]

jobs:
    pre-job:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel redundant workflows
              uses: technote-space/auto-cancel-redundant-workflow@v1

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install vercel
              run: npm i vercel -g
              
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Deploy landing page
              run: |
                export TEST=$(vercel --token $VERCEL_TOKEN) && echo "$TEST"
                curl -H "Content-Type: application/json" -d "{\"username\": \"Vercel\", \"content\": \"$TEST\"}" $WEBHOOK
                curl -H "Content-Type: application/json" -d "{\"username\": \"Vercel\", \"content\": \"$BRANCH\"}" $WEBHOOK
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_LANDING_ORG }}
                  WEBHOOK: ${{secrets.WEBHOOK}}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LANDING_PROJ }}
                  BRANCH : ${{ steps.extract_branch.outputs.branch }}
            - name: Show logs
              run: vercel logs metapass-v2-anoushk1234.vercel.app --token $VERCEL_TOKEN
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_LANDING_ORG }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_LANDING_PROJ }}
